apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gospeed-certs
  namespace: gospeed
  labels:
    app.kubernetes.io/name: gospeed
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
